version: "3"
services:
  db_auth:
    image: postgres
    restart: always
    ports:
      - "5440:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

  db_task_tracker:
    image: postgres
    restart: always
    ports:
      - "5441:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

  db_billing:
    image: postgres
    restart: always
    ports:
      - "5442:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

  kafka:
    image: wurstmeister/kafka
    restart: on-failure
    links:
    - zookeeper
    ports:
    - 9092:9092
    environment:
      KAFKA_BROKER_ID: '1'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_ADVERTISED_HOST_NAME: 'localhost'
      KAFKA_ADVERTISED_PORT: '9092'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
    - 2181:2181
