openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger task_tracker
  description: task tracker service
paths:
  /tasks/:
    post:
      description: Create new task
      operationId: createTask
      requestBody:
        description: Task data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /tasks/reassign/:
    post:
      description: Reassign all tasks
      operationId: reassignTasks
      requestBody:
        description: Empty data
        required: false
        content:
          application/json: {}
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ok'


components:
  schemas:
    TaskCreate:
      type: object
      required:
        - title
        - description
        - assigneeID
      properties:
        title:
          type: string
        description:
          type: string
        assigneeID:
          type: string
          format: uuid

    Task:
      type: object
      required:
        - jiraID
        - title
        - assigneeID
        - reporterID
        - status
        - createdAt
        - updatedAt
      properties:
        jiraID:
          type: integer
        title:
          type: string
        assigneeID:
          type: string
          format: uuid
        reporterID:
          type: string
          format: uuid
        status:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string

    Ok:
      type: object
      required:
        - status
      properties:
        status:
          type: string